#!/bin/bash

sudo apt-get install gnupg2

# INSTALL RUBY

# gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
# OR
curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

curl -L https://get.rvm.io | bash -s stable --ruby
rvm get stable --autolibs=enable
rvm install "ruby-2.4.2"
rvm --default use ruby-2.4.2

# INSTALL NODE
sudo curl -o /usr/local/bin/n https://raw.githubusercontent.com/visionmedia/n/master/bin/n
sudo chmod +x /usr/local/bin/n
sudo n stable

# INSTALL RAILS
gem update --system
rvm gemset use global
gem update
echo "gem: --no-document" >> ~/.gemrc

# /!\ RELOAD !!

gem install bundler
gem install nokogiri
gem install rails

# INSTALL POSTGRESQL
sudo apt-get install postgresql postgresql-contrib libpq-dev
gem install pg -v '0.21.0'

sudo apt-get install python-pip
sudo apt-get install tmux
pip install --user tmuxp

gem install mailcatcher

#git clone git@github.com:TheRealCodeKraft/cook-maker
#./cook-maker -a example -d "A skeleton app from codekraft cook maker" -v 0.0.31
