#!/bin/bash

#docker-compose up -d --no-deps --build api
docker-compose -f tools/docker-compose.yml run api rm /app/tmp/pids/server.pid
docker-compose -f tools/docker-compose.yml kill api
docker-compose -f tools/docker-compose.yml up -d --no-deps api
