#!/bin/bash

#docker-compose up -d --no-deps --build api
docker-compose -f tools/docker-compose.yml -p [[APP_NAME]] run api rm /app/tmp/pids/server.pid
docker-compose -f tools/docker-compose.yml -p [[APP_NAME]] kill api
docker-compose -f tools/docker-compose.yml -p [[APP_NAME]] up -d --no-deps api
