version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'example'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  api:
    depends_on:
      - 'postgres'
      - 'redis'
    build: ./api/
    ports:
      - '3000:3000'
    volumes:
      - './api:/app'
    env_file:
      - '.env'

  frontend:
    depends_on:
      - 'api'
    build: ./frontend/
    ports: 
      - '3002:3002'
    volumes:
      - './frontend:/app'
      - /app/node_modules
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
