#!/bin/bash

while getopts a: option
do
 case "${option}"
 in
 a) app_name=${OPTARG};;
 esac
done

SOURCE=${BASH_SOURCE[0]}
local_dir="$( dirname $SOURCE)"

if [ -z "$app_name" ]; then
  echo -n "Missing application name : set it with -a option"
  exit 1
fi

sudo docker rm cook-maker
sudo docker build -t cook-maker $local_dir #--no-cache
sudo docker run -it -v $(pwd):/build -e name=$app_name --name cook-maker-$app_name cook-maker
