#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
local_dir="$( dirname $SOURCE)"

sudo docker build -t cook-maker $local_dir
sudo docker rm cook-maker
sudo docker run -it -v $(pwd):/build --name cook-maker cook-maker
